name: mpi_new

description: HR MP Logistics.

publish_to: "none"

version: 1.0.18+44 #updated 22/10/24 //chưa release//hard

environment:
  sdk: ">=3.1.5 <4.0.0"
dependencies:
  analog_clock: ^0.1.1
  # awesome_dialog: ^3.1.0
  awesome_dialog: ^3.2.1
  # build_runner: ^2.4.6
  build_runner: ^2.4.9
  # carousel_slider: ^4.2.1
  carousel_slider: ^5.0.0
  # connectivity_plus: ^6.0.3
  connectivity_plus: ^6.1.0
  # cupertino_icons: ^1.0.2
  cupertino_icons: ^1.0.8
  # date_format: ^2.0.7
  date_format: ^2.0.9
  # device_info_plus: ^9.1.0
  device_info_plus: ^10.1.2
  # dio: ^5.3.0
  dio: ^5.7.0
  dropdown_button2: ^2.3.9
  # easy_localization: ^3.0.1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  # flutter_bloc: ^8.1.3
  flutter_bloc: ^8.1.6
  # flutter_calendar_carousel: ^2.4.2
  flutter_calendar_carousel: ^2.4.3
  # flutter_datetime_picker_plus: ^2.1.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_easyloading: ^3.0.5
  flutter_jailbreak_detection: ^1.10.0
  # flutter_launcher_icons: ^0.13.1
  flutter_launcher_icons: ^0.14.0
  # flutter_native_splash: ^2.3.5
  flutter_native_splash: ^2.3.13
  flutter_pdfview: ^1.3.2
  # flutter_slidable: ^3.0.1
  flutter_slidable: ^3.1.1
  # flutter_spinkit: ^5.2.0
  flutter_spinkit: ^5.2.1
  # flutter_widget_from_html: ^0.14.6
  flutter_widget_from_html: ^0.15.2
  # geolocator: ^10.1.0
  geolocator: ^12.0.0
  # get_it: ^7.6.4
  get_it: ^7.7.0
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  # image_picker: ^1.0.4
  image_picker: ^1.1.2
  # injectable: ^2.3.2
  injectable: ^2.4.2
  # injectable_generator: ^2.4.1
  injectable_generator: ^2.6.0
  # launch_review: ^3.0.1
  # local_auth: ^2.1.7
  local_auth: ^2.3.0
  # logger: ^2.0.2+1
  # logging: ^1.1.0
  # logging_appenders: ^1.2.0+1
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  # open_file_plus: ^3.4.1
  open_file_plus: ^3.4.1+1
  # package_info_plus: ^4.0.2
  package_info_plus: ^8.0.2
  # path_provider: ^2.1.1
  path_provider: ^2.1.4
  # permission_handler: ^11.0.1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  responsive_framework: ^0.2.0
  # shared_preferences: ^2.2.2
  shared_preferences: ^2.2.3
  # shimmer: ^2.0.0
  shimmer: ^3.0.0
  sprintf: ^7.0.0
  # tiengviet: ^0.5.0
  tiengviet: ^1.0.0
  timeline_tile: ^2.0.0
  # url_launcher: ^6.2.1
  url_launcher: ^6.3.0
  r_get_ip: ^0.1.3
  # firebase_messaging: ^15.1.0
  firebase_messaging: ^15.0.0
  firebase_core: ^3.1.1

  # firebase_core: ^2.16.0
  # firebase_messaging: ^14.6.8
  # flutter_local_notifications: ^16.1.0
  flutter_local_notifications: ^17.2.3
  cached_network_image: ^3.3.0
  flutter_inappwebview: ^5.8.0
  # flutter_screenutil: ^5.9.0
  flutter_screenutil: ^5.9.3
  # flutter_cache_manager: ^3.3.2
  flutter_cache_manager: ^3.4.1
  # rxdart: ^0.27.7
  rxdart: ^0.28.0

dev_dependencies:
  chewie: ^1.7.1
  chewie_audio: ^1.5.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/old/
    - assets/ca/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/open_sans_bold.ttf
        - asset: assets/fonts/open_sans_normal.ttf
          weight: 600
flutter_native_splash:
  color: "#ffc700"
  image: assets/icons/logo.png
  color_dark: "#ffc700"
  image_dark: assets/icons/logo.png
  android: true
  ios: true

flutter_icons:
  image_path: assets/icons/logo.png
  # image_path_android: assets/launcher/ic.png
  android: true
  ios: true
